version: '3.8'

services:
    fintrack_backend:
        container_name: fintrack_backend
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        command: "uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - ./:/code